### ISSUE TITLE
`permission denied` error when installing on Ubuntu

### ISSUE THREAD

**Issue by TheGrimmScientist** [CivilServiceUSA/civil-services-geojson-app#3]
#### Overview:

Error when installing this on Ubuntu 16.

#### Acceptance Criteria:

Acceptance criteria is being able to install it on Ubuntu.

#### Steps to Duplicate _( required for bug reports )_:

On a fresh Ubuntu,

I installed `yarn` per the docs:

    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt update
    sudo apt install yarn

After cloning the repo locally and `cd`ing into the project, I run 

    yarn run build-linux

and get the following error:

    yarn run v0.19.1
    $ build --linux 
    sh: 1: build: Permission denied
    error Command failed with exit code 126.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

`sudo`ing the command doesn't help either.

#### System Info _( required for bug reports )_:

Ubuntu 16.04.  Using whatever the default terminal is.

**Comment by manifestinteractive** [comment]
@TheGrimmScientist Error 126 means that a command was not executable, which might actually be a permissions issue on an executable ... judging from what the internet says anyway.

Is there any chance you did not run `yarn install` ?  That's required before `yarn run build-linux` will work :)

**Comment by manifestinteractive** [comment]
@TheGrimmScientist I actually just tested this locally on an Ubuntu 16.04 Desktop and it worked just fine.  I am wondering if you could try running the following:

```
cd /path/to/civil-services-geojson-app
yarn install
build --linux
```
